package com.example.recipe.ui.viewDataModels

data class SearchAdvancedFilterDialogViewData (
    val cuisine: String?,
    val diet: String?,
    val intolerances: String?,
    val mealType: String?,
    val maxReadyTime: Int?,
    val minCaffeine: Int?,
    val maxCaffeine: Int?,
    val minCalcium:Int?,
    val maxCalcium: Int?,
    val minCarbs: Int?,
    val maxCarbs: Int?,
    val minCholesterol: Int?,
    val maxCholesterol: Int?,
    val minFat: Int?,
    val maxFat: Int?,
    val minFiber: Int?,
    val maxFiber: Int?,
    val minIron: Int?,
    val maxIron: Int?,
    val minProtein: Int?,
    val maxProtein: Int?,
    val minSatFat: Int?,
    val maxSatFat: Int?,
    val minSodium: Int?,
    val maxSodium: Int?,
    val minSugar: Int?,
    val maxSugar: Int?,
    val minZinc: Int?,
    val maxZinc: Int?,
)